# Generated by Django 5.0.3 on 2026-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_word_delete_demouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(default='profile/default.png', upload_to='profile/')),
                ('cover_pic', models.ImageField(default='cover/default.png', upload_to='cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
